root: true
env:
  node: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
rules:
  # Parameter dürfen auch any sein
  "@typescript-eslint/explicit-module-boundary-types":
    - error
    - allowArgumentsExplicitlyTypedAsAny: true
  # Keine Semikolon
  "@typescript-eslint/semi":
    - error
    - never
  # Funktionen benötigen einen Rückgabetyp
  "@typescript-eslint/explicit-function-return-type":
    - error
  # Allow "any"
  "@typescript-eslint/no-explicit-any":
    - off
  # Allow empty interface
  "@typescript-eslint/no-empty-interface":
    - off
